# Generated by Django 4.2.3 on 2023-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
